apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: system-credentials
spec:
  action: Audit
  file:
    matchDirectories:
    - dir: /etc/pki/
      readOnly: true
      recursive: true
    - dir: /etc/ssl/
      readOnly: true
      recursive: true
    - dir: /usr/local/share/ca-certificates/
      readOnly: true
      recursive: true
    matchPaths:
    - path: /etc/ca-certificates.conf
      readOnly: true
    - path: /etc/groups
      readOnly: true
    - path: /etc/passwd
      readOnly: true
    - path: /root/.ssh/authorized_keys
      readOnly: true
  message: ALERT! Detected modification of credentials.
  nodeSelector:
    matchLabels:
      kubearmor.io/hostname: '*'
  process:
    matchPaths:
    - execname: certutil
  severity: 1
  tags:
  - FIGHT
  - MITRE
  - MITRE_T1552_unsecured_credentials
  - NIST
  - NIST-800-53-r5
  - NIST_SA
  - NIST_SA-20
  - T1140
  - T1552
  - T1555
